#server:
#  port: 8082
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/bankdb?useSSL=false
#    username : root
#    password : Gudli@2001
#
#  jpa:
#    hibernate.ddl-auto : update
#    properties.hibernate.dialect:  org.hibernate.dialect.MySQLDialect
#    show-sql: true
#  mvc.pathmatch.matching-strategy: ant_path_matcher
#  driver-class-name : com.mysql.cj.jdbc.Driver
#
#springfox.documentation.swagger-ui.enabled: true
